# Generated by Django 5.0.6 on 2024-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('withdraw_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
