# Generated by Django 5.0.6 on 2024-10-05 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_profit_or_loss', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('trades_count', models.IntegerField(default=0)),
            ],
        ),
    ]
