# Generated by Django 5.0.6 on 2024-10-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_monthlyperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPerformance',
        ),
    ]
